name: food_app
description: "Food ordering app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.6.1
  pocketbase: ^0.20.0
  json_annotation: ^4.9.0
  font_awesome_flutter: ^10.8.0
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.2
  url_launcher: ^6.3.1
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  flutter_map_location_marker: ^9.1.1
  flutter_map_math: ^0.1.7
  flutter_secure_storage: ^9.2.2
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true